[package]
name = "firefront-gis"
version = "0.3.4"
description = "GIS application for Firefighters"
authors = ["Donat Fortini"]
edition = "2024"

[lib]
name = "firefront_gis_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
chrono = "0.4.44"
directories = "6.0.0"
edit-distance = "2.2.2"
futures-util = "0.3.32"
geo = "0.33.1"
geo-types = "0.7.19"
geojson = "1.0.0"
geozero = "0.15.1"
image = { version = "0.25.10", default-features = false, features = [
    "jpeg",
    "png",
    "tiff",
] }
lazy_static = "1.5.0"
regex = "1.12.3"
reqwest = { version = "0.13.3", features = ["stream", "hickory-dns"] }
rusqlite = { version = "0.39.0", features = ["bundled"] }
scraper = "0.27.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
shapefile = "0.8.0"
tauri = { version = "2.11.2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2.7.1"
tauri-plugin-shell = "2.3.5"
thiserror = "2.0.18"
tiff = "0.11.3"
tokio = { version = "1.52.3", default-features = false, features = [
    "rt-multi-thread",
    "macros",
    "fs",
    "process",
    "io-util",
] }
wkt = "0.14.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.10.1"
