[package]
name = "firefront-gis-ui"
version = "0.2.2"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "HtmlSelectElement",
    "HtmlImageElement",
] }
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1.7"
serde_json = "1.0.140"

gloo-timers = "0.3.0"
gloo-utils = "0.2.0"
yew-router = "0.18.0"
stylist = { version = "0.13.0", features = ["yew"] }

[workspace]
members = ["src-tauri"]


[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
